[package]
name = "input-api"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
shared = { path = "../../shared" }

[dependencies.bevy]
version = "0.15.3"
default-features = false
features = []
