[workspace]
resolver = "3"
name = "the-cure"
version = "0.1.0"
publish = false
members = [
    "shared",
    "client",
    "server",
    "launcher",
    "renderer/renderer-api",
    "renderer/renderer-ratatui",
    "input/input-api",
    "input/input-crossterm"
]
